neos_eventsourcing:
  stores:
    blog:
      eventTableName: blog_events
      storage: Neos\EventSourcing\EventStore\Storage\Doctrine\DoctrineEventStorage
      eventPublisherTransport: Neos\EventSourcing\SymfonyBridge\EventPublisher\Transport\ConsoleCommandTransport
    user:
      eventTableName: user_events
      storage: Neos\EventSourcing\EventStore\Storage\Doctrine\DoctrineEventStorage
      eventPublisherTransport: Neos\EventSourcing\SymfonyBridge\EventPublisher\Transport\ConsoleCommandTransport
