FROM mysql:8.0
MAINTAINER Timo Nussbaum <timo.nussbaum@gmx.de>

#ADD conf.d /etc/mysql/conf.d
#ADD mysql-datadir /var/lib/mysql

# Manually set up the needed environment variables
ENV MYSQL_ROOT_PASSWORD 'password'

